name: Package and Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read package.json INFO
        id: info
        uses: jaywcjlove/github-action-package@main
      
      - run: echo "version - ${{ steps.info.outputs.version }}"

      - name: Check if tag exist
        id: checkTag
        uses: mukunku/tag-exists-action@v1.4.0
        if: steps.info.outputs.version != ''
        with:
          tag: "v${{steps.info.outputs.version}}"

      - name: Install Node.js
        if: steps.checkTag.outputs.exists == 'false'
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Generate extension package
        run: pnpm vsce package

      - name: Publish extension to vscode
        run: pnpm vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish extension to Open VSX
        run: pnpm ovsx publish
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{steps.info.outputs.version}}"
          files: "*.vsix"

